[libraries]
# Micronaut
micronaut-aws-function-aws = { module = "io.micronaut.aws:micronaut-function-aws" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-serde-api = { module = "io.micronaut.serde:micronaut-serde-api" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-validation = { module = "io.micronaut:micronaut-validation" }


aws-lambda-java-events = { module = 'com.amazonaws:aws-lambda-java-events' }
jackson-annotations = { module = 'com.fasterxml.jackson.core:jackson-annotations' }
